# .github/workflows/pr-build.yml
name: pre-release builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    uses: ./build-windows.yml

  build-linux:
    uses: ./build-linux.yml