# .github/workflows/pr-build.yml
name: pre-release builds

on:
  push:
    branches:
      - main
  #      - github-workflow # todo delete later
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install lxml
          pip install pyinstaller

      - name: clean previous builds
        run: |
          rmdir build -r -force -ErrorAction SilentlyContinue || true
          rmdir dist -r -force -ErrorAction SilentlyContinue || true

      - name: build with pyinstaller (windows)
        run: pyinstaller meikipop.win.x64.spec

      - name: build dictionary
        run: python -m scripts.build_dictionary

      - name: build windows archive
        run: |
          mkdir dist/meikipop
          mv jmdict_enhanced.pkl dist/meikipop/
          mv dist/meikipop.exe dist/meikipop/
          powershell -Command "Compress-Archive -Path dist/meikipop -DestinationPath dist/meikipop.x64.zip"

      - name: upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: meikipop-windows-x64-pr
          path: dist/meikipop.x64.zip

  build-linux:
    runs-on: ubuntu-latest
    #    container: ubuntu:22.04

    steps:
      - name: Prepare container
        run: |
          apt-get update
          apt-get install -y sudo

      - name: Install Linux (Apt) dependencies
        run: |
          sudo apt-get install -y \
            patchelf \
            libgl1 \
            libxkbcommon-x11-0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-render-util0 \
            libxcb-xinerama0 \
            libxcb-shape0 \
            libxcb-randr0 \
            libxcb-shm0 \
            libxcb-xfixes0

      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install lxml
          pip install pyinstaller
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: clean previous builds
        run: rm -rf build dist || true

      - name: build appimage
        run: |
          pyinstaller meikipop.linux.x64.spec
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          mv dist/meikipop AppDir/usr/bin/
          chmod +x AppDir/usr/bin/meikipop
          cp resources/meikipop.png AppDir/usr/share/icons/hicolor/256x256/apps/meikipop.png
          cp resources/meikipop.desktop AppDir/usr/share/applications/meikipop.desktop
          ./linuxdeploy-x86_64.AppImage --appdir AppDir --executable AppDir/usr/bin/meikipop --desktop-file AppDir/usr/share/applications/meikipop.desktop --icon-file AppDir/usr/share/icons/hicolor/256x256/apps/meikipop.png --output appimage

      - name: build dictionary
        run: python -m scripts.build_dictionary

      - name: build linux archive
        run: |
          mkdir dist/meikipop/
          mv meikipop-x86_64.AppImage dist/meikipop/meikipop.AppImage
          mv jmdict_enhanced.pkl dist/meikipop/
          tar -czvf dist/meikipop.linux.x64.tar.gz -C dist/ meikipop

      - name: upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: meikipop-linux-x64-pr
          path: dist/meikipop.linux.x64.tar.gz